name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install firebase-admin ipython matplotlib myst_parser numpydoc openbb pandas polars pydantic pyrate_limiter python-decouple sphinx sphinx-copybutton sphinx-design sphinx_rtd_theme sphinxext-opengraph
      - name: Add Environment secrets
        run: |
          echo ${{ secrets.MODELLING_101_FIREBASE_SERVICE_ACCOUNT_JSON }} > ./env/modelling-101.json; echo 'DATA_PROVIDER = "${{ secrets.DATA_PROVIDER }}"\nTICKER_SYMBOLS_LIST = "${{ secrets.TICKER_SYMBOLS_LIST }}"\nFIRESTORE_SERVICE_ACCOUNT = "${{ secrets.FIRESTORE_SERVICE_ACCOUNT }}"' > ./.env;
      - name: Sphinx build
        run: |
          sphinx-build docs _build
      - name: Add CNAME for custom domain
        run: |
          echo 'model.calvin.sg' > ./_build/CNAME
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
